export const SLIDE_LIST_REQUEST = 'SLIDE_LIST_REQUEST'
export const SLIDE_LIST_SUCCESS = 'SLIDE_LIST_SUCCESS'
export const SLIDE_LIST_FAIL = 'SLIDE_LIST_FAIL'

export const SLIDE_DELETE_REQUEST = 'SLIDE_DELETE_REQUEST'
export const SLIDE_DELETE_SUCCESS = 'SLIDE_DELETE_SUCCESS'
export const SLIDE_DELETE_FAIL = 'SLIDE_DELETE_FAIL'

export const SLIDE_UPDATE_REQUEST = 'SLIDE_UPDATE_REQUEST'
export const SLIDE_UPDATE_SUCCESS = 'SLIDE_UPDATE_SUCCESS'
export const SLIDE_UPDATE_FAIL = 'SLIDE_UPDATE_FAIL'
export const SLIDE_UPDATE_RESET = 'SLIDE_UPDATE_RESET'


export const SLIDE_DETAILS_REQUEST = 'SLIDE_DETAILS_REQUEST'
export const SLIDE_DETAILS_SUCCESS = 'SLIDE_DETAILS_SUCCESS'
export const SLIDE_DETAILS_FAIL = 'SLIDE_DETAILS_FAIL'
export const SLIDE_DETAILS_RESET = 'SLIDE_DETAILS_RESET'
